### ISSUE TITLE
Meta-issue for ergonomic advancements

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#101]
Followup to #90.  Here's the grander scheme as I see it:

* [x] Add inherent methods
  * [x] To HLists and Coproducts (done in #99)
  * [x] Anything else? (checked while doing #103)
  * [ ] For HMappable and friends now that the impls `for &Type` are gone
* [x] Reexport the most important things at the root (done in #103)
  * HCons, HNil, Coproduct, HList
  * What else from the other modules?
* [x] Introduce a prelude module for traits that need to be imported to be used (done in #103)
  * extension traits for types outside frunk
  * things like `HMappable` that have impls for `&HCons`
    * Or we can take this opportunity to introduce a more general `Mappable` trait
* ~~[#] **(maybe!)** Rename the traits in line with the rust convention of `Verb::verb`~~
  * I don't think this is worth it right now
* Take advantage of the new features in docs and examples
  * use turbofish!
  * no more `use frunk::hlist::*`
  * [x] in `README.md`
  * [ ] in examples
    * if necessary, add `frunk` as dev dependency to frunk-core so doc examples can use frunk's prelude (or add a prelude to frunk-core, but I think having two makes it harder to maintain)

**Comment by Centril** [comment]
> What else from the other modules?

Probably `Generic`?

**Comment by lloydmeta** [comment]
> Probably `Generic`?

If we're adding `Generic`, then I would also suggest adding `LabelledGeneric` too.

One thing I've been wondering is, in addition to Serde, are there any other super commonly-used crates that we should offer feature-gated `derive`s for?

**Comment by Centril** [comment]
Not necessarily derives.. but itertools, rayon, futures, and standard library traits for coproducts?

**Comment by lloydmeta** [comment]
> Not necessarily derives.. but itertools, rayon, futures, and standard library traits for coproducts?

Nice one! Starting with std. lib traits might be a good idea :D

**Comment by ExpHP** [comment]
So this is now down to the final finishing touches, that I'm trying to finish right now:

* Basically, now that the impls for `&HList` and `&Coproduct` are gone, it is possible to add inherent methods for `map` and `fold{,l,r}`.  I want to get these in before 0.2.0 to make sure the design is cohesive.  (This will remove those traits from the prelude, which would be a breaking change if we wait on this)

* I also want to fix all of the doc examples to show the necessary `use` statements.  Luckily, doc tests for `frunk_core` are allowed to depend on `frunk`, so that the new idiomatic paths can be shown.

After these changes, I think I'll be satisfied enough with the design to ship it.

**Comment by Centril** [comment]
@ExpHP Thanks for all the work you've put in <3

Maybe we should also allow `#[derive(Generic)]` for `enum`s as a final advancement in 0.2 where they translate to `Coprod!` ?

**Comment by lloydmeta** [comment]
> After these changes, I think I'll be satisfied enough with the design to consider it shippable.

+ 💯  

Adding `derive` for `Generic`/`LabelledGeneric` can be done in a backwards-compatible way, but I think there was talk about reifying indices; is that something we want to include in 0.2 ? Do we foresee breaking backwards compatibility there ? FWIW, I don't *think* so, but just wanted to doublecheck.

**Comment by ExpHP** [comment]
Good catch; most of the feature can be added backwards compatibly, but changing `Here` to a unit struct will be breaking and so it might be good to slip that bit in before 0.2.0.

**Comment by ExpHP** [comment]
Yuck, I ran into a couple of snags while making the PR to remove glob imports from examples:

* As mentioned, `map` and `fold` should be inherent methods.
* Coproduct should impl `ToRef` or similar and lose the `CoproductFoldable for &Coproduct` impls
* `Poly`, `Func`, `ToRef` should be reexported at the root.
* The character enums `labelled::{a, b, c, ...}` basically need to be glob imported.  These should be moved into a dedicated module that is designed to be glob-imported.  (in my not-yet-submitted PR I use `frunk::labelled::chars::*`)

Each of these in turn affect examples and tests.

Initially, I figured I would just slip in a fix for the first bullet as the first few commits in the PR, but as more things have cropped up the PR has gotten a bit out of hand, with some later commits changing/undoing things done in earlier commits.  I think I'm going to need to find a way to break it into a number of chunks that are individually more palatable...

**Comment by ExpHP** [comment]
P.S. I also dislike the location of `Poly`, `Func`, `ToRef`, `Here`, and `There` in `hlist`, and it will be a breaking change to move them somewhere else in the future.

`Here/There` could get their own `indices` module (where they will be very lonely until reified indices), but I wasn't sure about the others.

**Comment by Centril** [comment]
Soon! I'll have to add the Generic first in a PR. I'll do a pull request today.

**Comment by ExpHP** [comment]
*pokes @Centril*

Has progress been made on this? :slightly_smiling_face: I'm kind of eager to push things forward, and I don't foresee any difficulty with adding the Generic impls in a non-breaking update (unless there's something I'm not aware of)
